version: '3'
services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    ports:
      - '1234:1234'

  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '8080:80'
    depends_on: 
      - api